# Generated by Django 5.2.8 on 2025-11-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_reminder_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the product/service', max_length=200, unique=True, verbose_name='Product Name')),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, help_text='Product description', verbose_name='Description')),
                ('pillar', models.CharField(choices=[('project_management', 'Project/Task Management'), ('technical_sales', 'Technical and Sales'), ('development', 'Development')], help_text='Which pillar this product belongs to', max_length=50, verbose_name='Pillar')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this product is currently available', verbose_name='Active')),
                ('is_default', models.BooleanField(default=False, help_text='Default product for new registrations', verbose_name='Default Product')),
                ('order', models.IntegerField(default=0, help_text='Order in which products are displayed', verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['order', 'name'],
            },
        ),
    ]
