# Generated by Django 5.2.8 on 2025-11-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=2500.0, help_text='Default price for this product (ZAR)', max_digits=10, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='time_from',
            field=models.TimeField(blank=True, help_text='Default start time for tasks created from this product', null=True, verbose_name='Time From'),
        ),
    ]
