# Generated by Django 5.2.8 on 2025-11-29 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_product'),
        ('crm', '0009_request_case'),
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecommercecompany',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Product/service selected during registration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='common.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='ecommercecompany',
            name='registration_deal',
            field=models.ForeignKey(blank=True, help_text='Deal created for this company registration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_companies', to='crm.deal'),
        ),
    ]
