# Generated by Django 5.2.8 on 2025-11-29 11:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FCMDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], default='android', max_length=20)),
                ('device_id', models.CharField(blank=True, help_text='Device identifier', max_length=255, null=True)),
                ('device_name', models.CharField(blank=True, help_text='Device name/model', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FCM Device',
                'verbose_name_plural': 'FCM Devices',
            },
        ),
        migrations.CreateModel(
            name='FCMMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('fcm_message_id', models.CharField(blank=True, help_text='FCM message ID from response', max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='fcm.fcmdevice')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fcm_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FCM Message',
                'verbose_name_plural': 'FCM Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='fcmdevice',
            index=models.Index(fields=['user', 'is_active'], name='fcm_fcmdevi_user_id_439395_idx'),
        ),
        migrations.AddIndex(
            model_name='fcmdevice',
            index=models.Index(fields=['token'], name='fcm_fcmdevi_token_0a40e0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fcmdevice',
            unique_together={('user', 'token')},
        ),
        migrations.AddIndex(
            model_name='fcmmessage',
            index=models.Index(fields=['user', 'status'], name='fcm_fcmmess_user_id_b9f648_idx'),
        ),
        migrations.AddIndex(
            model_name='fcmmessage',
            index=models.Index(fields=['device', 'status'], name='fcm_fcmmess_device__c95cb8_idx'),
        ),
        migrations.AddIndex(
            model_name='fcmmessage',
            index=models.Index(fields=['created_at'], name='fcm_fcmmess_created_7c688e_idx'),
        ),
    ]
