# Generated by Django 5.2.8 on 2025-11-29 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
        ('fcm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_enabled', models.BooleanField(default=True, help_text='Master switch for all notifications')),
                ('notify_orders_created', models.BooleanField(default=True, help_text='Notify when new orders are created')),
                ('notify_orders_paid', models.BooleanField(default=True, help_text='Notify when orders are paid')),
                ('notify_orders_shipped', models.BooleanField(default=True, help_text='Notify when orders are shipped')),
                ('notify_orders_delivered', models.BooleanField(default=True, help_text='Notify when orders are delivered')),
                ('notify_orders_cancelled', models.BooleanField(default=True, help_text='Notify when orders are cancelled')),
                ('notify_tasks_assigned', models.BooleanField(default=True, help_text='Notify when tasks are assigned to you')),
                ('notify_tasks_created', models.BooleanField(default=True, help_text='Notify when new tasks are created (if you are responsible)')),
                ('notify_tasks_completed', models.BooleanField(default=False, help_text='Notify when tasks you created are completed')),
                ('notify_tasks_due_soon', models.BooleanField(default=True, help_text='Notify when tasks are approaching due date')),
                ('notify_chat_messages', models.BooleanField(default=True, help_text='Notify when you receive new chat messages')),
                ('notify_deals_created', models.BooleanField(default=True, help_text='Notify when deals are created (if you are assigned)')),
                ('notify_deals_updated', models.BooleanField(default=True, help_text='Notify when deals are updated (if you are assigned)')),
                ('notify_deals_won_lost', models.BooleanField(default=True, help_text='Notify when deals are won or lost')),
                ('notify_payments_success', models.BooleanField(default=True, help_text='Notify when payments are successful')),
                ('notify_payments_failed', models.BooleanField(default=True, help_text='Notify when payments fail')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Notification Settings',
                'verbose_name_plural': 'User Notification Settings',
            },
        ),
        migrations.RemoveIndex(
            model_name='fcmdevice',
            name='fcm_fcmdevi_user_id_439395_idx',
        ),
        migrations.RemoveIndex(
            model_name='fcmmessage',
            name='fcm_fcmmess_user_id_b9f648_idx',
        ),
        migrations.AlterUniqueTogether(
            name='fcmdevice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='fcmdevice',
            name='company',
            field=models.ForeignKey(default=0, help_text='Company this device is registered for', on_delete=django.db.models.deletion.CASCADE, related_name='fcm_devices', to='ecommerce.ecommercecompany'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fcmmessage',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company context for this message', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fcm_messages', to='ecommerce.ecommercecompany'),
        ),
        migrations.AlterField(
            model_name='fcmdevice',
            name='token',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='fcmdevice',
            unique_together={('user', 'company', 'token')},
        ),
        migrations.AddIndex(
            model_name='fcmdevice',
            index=models.Index(fields=['user', 'company', 'is_active'], name='fcm_fcmdevi_user_id_24cdb5_idx'),
        ),
        migrations.AddIndex(
            model_name='fcmdevice',
            index=models.Index(fields=['company', 'is_active'], name='fcm_fcmdevi_company_e74675_idx'),
        ),
        migrations.AddIndex(
            model_name='fcmmessage',
            index=models.Index(fields=['user', 'company', 'status'], name='fcm_fcmmess_user_id_7b5b4d_idx'),
        ),
        migrations.AddIndex(
            model_name='fcmmessage',
            index=models.Index(fields=['company', 'status'], name='fcm_fcmmess_company_f793f2_idx'),
        ),
        migrations.AddField(
            model_name='usernotificationsettings',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notification_settings', to='ecommerce.ecommercecompany'),
        ),
        migrations.AddField(
            model_name='usernotificationsettings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='usernotificationsettings',
            index=models.Index(fields=['user', 'company'], name='fcm_usernot_user_id_641103_idx'),
        ),
        migrations.AddIndex(
            model_name='usernotificationsettings',
            index=models.Index(fields=['company', 'notifications_enabled'], name='fcm_usernot_company_749146_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usernotificationsettings',
            unique_together={('user', 'company')},
        ),
    ]
