# Generated by Django 5.2.8 on 2025-11-29 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_product_price_product_time_from'),
        ('crm', '0009_request_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Product/service associated with this deal (for registration deals)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='common.product', verbose_name='Product'),
        ),
    ]
